version: '2.4'
services:
  mysql:
    image: "mysql:5.6"
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mostest
      MYSQL_PASSWORD: mostest
      MYSQL_USER: mmuser
      MYSQL_DATABASE: mm_lighthouse_ci
    container_name: mattermost-lighthouse
    ports:
      - "3366:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
